// playback actions
export const PLAY_SONG = 'PLAY_SONG';
export const PAUSE_SONG = 'PAUSE_SONG';
export const SKIP_SONG = 'SKIP_SONG';
export const UPDATE_CURRENT_SONG = 'UPDATE_CURRENT_SONG';
export const UPDATE_PLAYBACK_STATE = 'UPDATE_PLAYBACK_STATE';

// queue actions
export const ADD_SONG = 'ADD_SONG';
export const REMOVE_SONG = 'REMOVE_SONG';
export const VOTE_SONG = 'VOTE_SONG';
export const UPDATE_QUEUE = 'UPDATE_QUEUE';
export const RESET_QUEUE = 'RESET_QUEUE';

// room actions
export const JOIN_ROOM_START = 'JOIN_ROOM_START';
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';
export const JOIN_ROOM_ERROR = 'JOIN_ROOM_ERROR';
export const CREATE_ROOM_START = 'CREATE_ROOM_START';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR';
export const LEAVE_ROOM = 'LEAVE_ROOM';
export const ROOM_INFO = 'ROOM_INFO';

// spotify actions
export const SPOTIFY_REQUEST_TOKEN = 'SPOTIFY_REQUEST_TOKEN';
export const SPOTIFY_REFRESH_TOKEN = 'SPOTIFY_REFRESH_TOKEN';
export const SPOTIFY_TOKEN_SUCCESS = 'SPOTIFY_TOKEN_SUCCESS';
export const SPOTIFY_TOKEN_ERROR = 'SPOTIFY_TOKEN_ERROR';
export const SPOTIFY_SEARCH_SUCCESS = 'SPOTIFY_SEARCH_SUCCESS';
export const SPOTIFY_SEARCH_ERROR = 'SPOTIFY_SEARCH_ERROR';
export const SPOTIFY_USER_SUCCESS = 'SPOTIFY_USER_SUCCESS';
export const SPOTIFY_USER_ERROR = 'SPOTIFY_USER_ERROR';
export const SPOTIFY_PLAYER_SUCCESS = 'SPOTIFY_PLAYER_SUCCESS';
export const SPOTIFY_PLAYER_ERROR = 'SPOTIFY_PLAYER_ERROR';
